# should be optimize as increment build & test
name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
          - NodeVersion: 20.9.x
            NodeVersionDisplayName: 20
            OS: ubuntu-latest
    name: Node.js v${{ matrix.NodeVersionDisplayName }} (${{ matrix.OS }})
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Git config user
        run: |
          git config --local user.name "tecvan-bot"
          git config --local user.email "fanwenjie.fe@bytedance.com"

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NodeVersion }}

      - name: Install Dependencies
        run: node common/scripts/install-run-rush.js install

      - name: Build
        run: node common/scripts/install-run-rush.js build --verbose

      - name: Test
        run: node common/scripts/install-run-rush.js build --verbose